services:
  - type: web
    name: nova-chatbot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
      - key: NODE_ENV
        value: production